package de.alexanderciupka.pokemon.constants;

/**
 * This class is auto-generated. Contains all the Ability IDs to avoid using
 * random IDs in source code, when checking for certain Abilities. This also
 * allows Abilities to be Renamed.
 * 
 * @author CutyCupy
 */

public class Abilities {

	public static final int KEINE = 0;
	public static final int DUFTNOTE = 1;//
	public static final int NIESEL = 2;//
	public static final int TEMPOSCHUB = 3;//
	public static final int KAMPFPANZER = 4;//
	public static final int ROBUSTHEIT = 5;//
	public static final int FEUCHTIGKEIT = 6;
	public static final int FLEXIBILITÄT = 7;//
	public static final int SANDSCHLEIER = 8;//
	public static final int STATIK = 9;//
	public static final int VOLTABSORBER = 10;//
	public static final int H2O_ABSORBER = 11;//
	public static final int DÖSIGKEIT = 12;//
	public static final int WOLKE_SIEBEN = 13;//
	public static final int FACETTENAUGE = 14;//
	public static final int INSOMNIA = 15;//
	public static final int FARBWECHSEL = 16;
	public static final int IMMUNITÄT = 17;//
	public static final int FEUERFÄNGER = 18;
	public static final int PUDERABWEHR = 19;//
	public static final int TEMPOMACHER = 20;//
	public static final int SAUGNAPF = 21;//
	public static final int BEDROHER = 22;//
	public static final int WEGSPERRE = 23;//
	public static final int RAUHAUT = 24;//
	public static final int WUNDERWACHE = 25;//
	public static final int SCHWEBE = 26;//
	public static final int SPORENWIRT = 27;//
	public static final int SYNCHRO = 28;//
	public static final int NEUTRALTORSO = 29;//
	public static final int INNERE_KRAFT = 30;//
	public static final int BLITZFÄNGER = 31;//
	public static final int EDELMUT = 32;//
	public static final int WASSERTEMPO = 33;//
	public static final int CHLOROPHYLL = 34;//
	public static final int ERLEUCHTUNG = 35;//
	public static final int FÄHRTE = 36;//
	public static final int KRAFTKOLOSS = 37;//
	public static final int GIFTDORN = 38;//
	public static final int KONZENTRATOR = 39;//
	public static final int MAGMAPANZER = 40;//
	public static final int AQUAHÜLLE = 41;//
	public static final int MAGNETFALLE = 42;//
	public static final int LÄRMSCHUTZ = 43;//
	public static final int REGENGENUSS = 44;//
	public static final int SANDSTURM = 45;//
	public static final int ERZWINGER = 46;//
	public static final int SPECKSCHICHT = 47;//
	public static final int FRÜHWECKER = 48;//
	public static final int FLAMMKÖRPER = 49;//TODO: Eggs?
	public static final int ANGSTHASE = 50;//TODO: Fliehen?
	public static final int ADLERAUGE = 51;//
	public static final int SCHERENMACHT = 52;//
	public static final int MITNAHME = 53;//TODO: Items?
	public static final int SCHNARCHNASE = 54;//
	public static final int ÜBEREIFER = 55;//
	public static final int CHARMEBOLZEN = 56;//
	public static final int PLUS = 57;//
	public static final int MINUS = 58;//
	public static final int PROGNOSE = 59;//
	public static final int WERTEHALTER = 60;//TODO: Items
	public static final int EXPIDERMIS = 61;//
	public static final int ADRENALIN = 62;//
	public static final int NOTSCHUTZ = 63;//
	public static final int KLOAKENSOSSE = 64;//
	public static final int NOTDÜNGER = 65;//
	public static final int GROSSBRAND = 66;//
	public static final int STURZBACH = 67;//
	public static final int HEXAPLAGA = 68;//
	public static final int STEINHAUPT = 69;//
	public static final int DÜRRE = 70;//
	public static final int AUSWEGLOS = 71;//
	public static final int MUNTERKEIT = 72;//
	public static final int PULVERRAUCH = 73;//
	public static final int MENTALKRAFT = 74;//
	public static final int PANZERHAUT = 75;//
	public static final int KLIMASCHUTZ = 76;//
	public static final int FUSSANGEL = 77;//
	public static final int STARTHILFE = 78;//
	public static final int RIVALITÄT = 79;//
	public static final int FELSENFEST = 80;//
	public static final int SCHNEEMANTEL = 81;//
	public static final int VÖLLEREI = 82;//TODO: Beeren
	public static final int KURZSCHLUSS = 83;//
	public static final int ENTLASTUNG = 84;//TODO: Items
	public static final int HITZESCHUTZ = 85;//
	public static final int WANKELMUT = 86;//
	public static final int TROCKENHEIT = 87;//
	public static final int DOWNLOAD = 88;//
	public static final int EISENFAUST = 89;//
	public static final int AUFHEBER = 90;//
	public static final int ANPASSUNG = 91;//
	public static final int WERTELINK = 92;//
	public static final int HYDRATION = 93;//
	public static final int SOLARKRAFT = 94;//
	public static final int RASANZ = 95;//
	public static final int REGULIERUNG = 96;//
	public static final int SUPERSCHÜTZE = 97;//
	public static final int MAGIESCHILD = 98;//TODO: Items
	public static final int SCHILDLOS = 99;//
	public static final int ZEITSPIEL = 100;//
	public static final int TECHNIKER = 101;//
	public static final int FLORASCHILD = 102;//
	public static final int TOLLPATSCH = 103;//TODO: Items
	public static final int ÜBERBRÜCKUNG = 104;//
	public static final int GLÜCKSPILZ = 105;//
	public static final int FINALSCHLAG = 106;//
	public static final int VORAHNUNG = 107;//
	public static final int VORWARNUNG = 108;//
	public static final int UNKENNTNIS = 109;//
	public static final int AUFWERTUNG = 110;//
	public static final int FILTER = 111;//
	public static final int SAUMSELIG = 112;//
	public static final int RAUFLUST = 113;//
	public static final int STURMSOG = 114;//
	public static final int EISHAUT = 115;//
	public static final int FELSKERN = 116;//
	public static final int HAGELALARM = 117;//
	public static final int HONIGMAUL = 118;//TODO: Items
	public static final int SCHNÜFFLER = 119;//TODO: Items
	public static final int ACHTLOS = 120;//
	public static final int VARIABILITÄT = 121;//TODO: Items
	public static final int PFLANZENGABE = 122;//
	public static final int ALPTRAUM = 123;//
	public static final int LANGFINGER = 124;//TODO: Items
	public static final int ROHE_GEWALT = 125;//
	public static final int UMKEHRUNG = 126;//
	public static final int ANSPANNUNG = 127;//TODO: Items
	public static final int SIEGESWILLE = 128;//
	public static final int SCHWÄCHLING = 129;//
	public static final int TASTFLUCH = 130;//
	public static final int HEILHERZ = 131;//
	public static final int FREUNDESHUT = 132;//
	public static final int BRUCHRÜSTUNG = 133;//
	public static final int SCHWERMETALL = 134;//
	public static final int LEICHTMETALL = 135;//
	public static final int MULTISCHUPPE = 136;//
	public static final int GIFTWAHN = 137;//
	public static final int HITZEWAHN = 138;//
	public static final int REICHE_ERNTE = 139;//TODO: Items
	public static final int TELEPATHIE = 140;//
	public static final int GEFÜHLSWIPPE = 141;//
	public static final int WETTERFEST = 142;//
	public static final int GIFTGRIFF = 143;//
	public static final int BELEBEKRAFT = 144;//
	public static final int BRUSTBIETER = 145;//
	public static final int SANDSCHARRER = 146;//
	public static final int WUNDERHAUT = 147;//
	public static final int ANALYSE = 148;//
	public static final int TRUGBILD = 149;//TODO
	public static final int DOPPELGÄNGER = 150;//TODO
	public static final int SCHWEBEDURCH = 151;//TODO 
	public static final int MUMIE = 152;//
	public static final int HOCHMUT = 153;//TODO
	public static final int REDLICHKEIT = 154;//
	public static final int HASENFUSS = 155;//
	public static final int MAGIESPIEGEL = 156;//TODO
	public static final int VEGETARIER = 157;//
	public static final int STROLCH = 158;//
	public static final int SANDGEWALT = 159;//
	public static final int EISENSTACHEL = 160;//
	public static final int TRANCE_MODUS = 161;//TODO: But probably not implemented
	public static final int TRIUMPHSTERN = 162;//
	public static final int TURBOBRAND = 163;//
	public static final int TERAVOLT = 164;//
}
